ACCESS_SERVER_LISTEN_ADDRESS=0.0.0.0
ACCESS_SERVER_LISTEN_PORT=16688
ACCESS_SERVER_TLS_ENABLED=true
ACCESS_SERVER_TLS_CERTIFICATES_DATA_ID=ploto.unified-access.tls-certificates
ACCESS_SERVER_TLS_CERTIFICATES_GROUP=ACCESS-SERVER
ACCESS_SERVER_HTTP3_ENABLED=true
ACCESS_SERVER_UPSTREAM_TLS_MODE=legacy_insecure
ACCESS_SERVER_UPSTREAM_TLS_CA_FILE=
ACCESS_SERVER_METRICS_LISTEN_ADDRESS=0.0.0.0
ACCESS_SERVER_METRICS_LISTEN_PORT=16689
ACCESS_SERVER_ACTIVATION_EVIDENCE_ENABLED=true
ACCESS_SERVER_INSTANCE_ID=access-0
ACCESS_SERVER_ACTIVATION_TOKEN=__ACTIVATION_TOKEN__
ACCESS_SERVER_INITIAL_CONFIG_TIMEOUT_MILLIS=30000
ACCESS_SERVER_MAX_REQUEST_BODY_SIZE=16777216
ACCESS_SERVER_TEST_MODE=false

ACCESS_SERVER_PROJECTS_DATA_ID=ploto.unified-access.projects
ACCESS_SERVER_ROUTE_DATA_ID_PREFIX=ploto.unified-access.route.
ACCESS_SERVER_ROUTE_GROUP=ACCESS-SERVER
ACCESS_SERVER_GRAY_DATA_ID=ploto.unified-access.gray-match
ACCESS_SERVER_NAMING_GROUP=DEFAULT_GROUP
ACCESS_SERVER_ZONE=local-demo

NACOS_SERVER_ADDRESSES=__RNACOS_IP__
NACOS_HTTP_PORT=8848
NACOS_GRPC_PORT=9848
NACOS_NAMESPACE=public
NACOS_TENANT=
NACOS_USERNAME=
NACOS_PASSWORD=
NACOS_CLIENT_VERSION=fiber-access-server/docker-demo

CAT_APP_KEY=
CAT_HOSTNAME=
CAT_IP=
CAT_ROUTER_ADDRESSES=
CAT_COLLECTOR_ADDRESSES=
